declare module 'react-native-paper';
declare module 'react-native-vector-icons/*';
declare module '@expo/vector-icons';
declare module 'expo-sqlite';
declare module 'expo-status-bar';
declare module 'react-native-chart-kit';
declare module 'expo-image-picker';
declare module 'expo-notifications';
declare module 'expo-constants'; 